# Use a more recent Node.js version
FROM node:18-alpine

WORKDIR /root

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN apk add --no-cache bash \
    && npm ci

# Cache node_modules for faster builds (Optional)
RUN mv node_modules node_modules_cache \
    && rm -rf /tmp/*
